"""What the last optimisation left behind.

``outputs/`` mirrors the most recent run and nothing else. It is emptied and
rewritten every time, deliberately: a folder that accumulates is a folder where
you cannot tell which motor a file describes, and every stale figure in it is a
figure someone can quote at you months later.

Nothing here is source. It is regenerated by running the optimiser again.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path
from typing import Dict, List, Optional

import numpy as np

from .design import DesignSpace
from .ric import save_ric

#: Written on every rewrite so it is obvious the folder is disposable.
README = """This folder is the output of the last optimisation, and only the last one.

It is emptied and rewritten every time the optimiser runs. Nothing in here is
source, nothing in here is committed, and nothing in here is worth editing --
run the optimiser again and it all comes back, describing whatever motor you
ran it on.

  result.json   the whole run: spec, limits, every legal design, statistics
  motors/       one .ric per legal design, ready to open in openMotor
  figures/      the figures from the report
"""


def _empty(folder: Path) -> None:
    """Removes the contents, keeps the folder.

    Only ever called on the outputs directory. Deleting and recreating the
    folder itself would break anything holding it open.
    """
    for child in folder.iterdir():
        if child.is_dir():
            shutil.rmtree(child, ignore_errors=True)
        else:
            child.unlink(missing_ok=True)


def write_run(result, base_motor: Dict, space: Optional[DesignSpace],
              out_dir: Path, figures: Optional[Dict[str, Path]] = None) -> List[Path]:
    """Replaces everything in ``out_dir`` with this run's data."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    _empty(out_dir)

    written: List[Path] = []
    (out_dir / "README.txt").write_text(README)
    written.append(out_dir / "README.txt")

    payload = result.to_dict() if hasattr(result, "to_dict") else dict(result)
    path = out_dir / "result.json"
    path.write_text(json.dumps(payload, indent=2))
    written.append(path)

    designs = payload.get("designs", [])
    if designs and space is not None:
        motors = out_dir / "motors"
        motors.mkdir(exist_ok=True)
        for index, design in enumerate(designs):
            x = design.get("x")
            if not x:
                continue
            name = "".join(c for c in str(design.get("designation", ""))
                           if c.isalnum()) or "design"
            target = motors / "{:02d}-{}.ric".format(index + 1, name)
            try:
                save_ric(target, space.to_motor(np.asarray(x, dtype=float)))
                written.append(target)
            except Exception:
                # One design failing to serialise must not cost the rest.
                continue

    if figures:
        folder = out_dir / "figures"
        folder.mkdir(exist_ok=True)
        for key, source in figures.items():
            if source is None or not Path(source).exists():
                continue
            target = folder / "{}{}".format(key, Path(source).suffix)
            shutil.copyfile(source, target)
            written.append(target)

    return written
